name: demokit-docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip

  - sphinx<7.0

  - sphinx_rtd_theme
  - sphinxcontrib-bibtex

    # Pip-only installs
  #- pip:

